Console.Write("Inserisci Il Nome Dell'Autore: ");
var autore = Console.ReadLine();
Console.Write("Inserisci Il Titolo Del Libro: ");
var titolo = Console.ReadLine();
Console.Write("Inserisci L'ISBN del libro: ");
var isbn =  long.Parse(Console.ReadLine());
Console.Write("Inserisci Il Numero Di Pagine Del Libro: ");
var pagine = int.Parse(Console.ReadLine());
Console.Write("Inserisci Il Peso Del Libro: ");
var peso = double.Parse(Console.ReadLine());
Console.Write("Inserisci La Larghezza Del Libro: ");
var larghezza = double.Parse(Console.ReadLine());
Console.Write("Inserisci L'Altezza Del Libro: ");
var altezza = double.Parse(Console.ReadLine());
Console.Write("Inserisci La Profondità Del Libro: ");
var profondità = double.Parse(Console.ReadLine());
Console.Write("Inserisci Il Numero Di Valutazioni Del Libro ");
var numerovalutazioni = int.Parse(Console.ReadLine());
Console.Write("Inserisci Il Valore Medio Delle Recensioni Del Libro: ");
var valutazione = double.Parse(Console.ReadLine());
Console.Write("Inserisci Se Il Libro è Disponibile In Versione Kindle: ");
var kindle = Console.ReadLine();
Console.Write("Inserisci Se Il Libro è Disponibile Con La Copertina Rigida: ");
var copertinarigida = Console.ReadLine();

Console.WriteLine("---------------------------------- Il Libro Di Oggi--------------------------------------");
Console.WriteLine();
Console.WriteLine(titolo + " di " + autore);
Console.WriteLine();
Console.WriteLine("-----------------------------------------------------------------------------------------");
Console.WriteLine();
Console.WriteLine("Informazioni Generiche:");
Console.WriteLine("ISBN: " + isbn);
Console.WriteLine("Numero Di Pagine: " + pagine + " Pagine");
Console.WriteLine("Peso Del Libro: " + peso + " Kg");
Console.WriteLine("Dimensioni Del Libro: " + larghezza + " x " + altezza + " x " + profondità + " cm");
Console.WriteLine();
Console.WriteLine("Informazioni Amazon:");
Console.WriteLine("Numero Di Recensioni: " + numerovalutazioni + " Recensioni");
Console.WriteLine("Valutazione Media: " + valutazione + " Stelline");
Console.WriteLine("Kindle Disponibile: " + kindle);
Console.WriteLine("Copertina Rigida: " + copertinarigida);
